version: "3"

services:
  backend:
    restart: always
    command: bash -c "python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    restart: always
    build:
      context: ./todo-frontend
      dockerfile: Dockerfile
    volumes:
      - react_build:/todo-frontend/build
volumes:
  react_build:
